[DAT-622] Payments Table
apiabroad/payment-service pull request #1
Opened 2022-06-01 17:30 UTC by przzz27

# [DAT-622](https://apiabroad.atlassian.net/browse/DAT-622)

Creates the base project structure to work on, containing:

- Models
- Schemas
- Tests
- pre-commit

based on fastapi

## Dependencies

- None yet

## Type of change
- [X] New feature (non-breaking change which adds functionality)

## How to test

1. Follow the [readme.md ](https://github.com/apiabroad/payment-service/blob/804130e1134ed14455d04c3611f31dbf4eb2838c/README.md)instructions to setup the payment service
2. Check that the table contains the columns / indexes described in [this ticket](https://apiabroad.atlassian.net/browse/DAT-622)
3. Additionally run `poetry run pytest` to run the unit tests

2022-06-01 17:45 UTC, seantbaier requested changes
- Add github actions

2022-06-23 21:08 UTC, bryancusatis approved these changes
I think this is good, we should just incorporate Aaron's modifications to the process once he is done for actions / docker / tests

2022-06-29 00:24 UTC, ascheffeapi commented on .github/workflows/lint-and-test.yml
> +      - name: Install dependencies
I dont think you need the `&& yarn` without cypress

2022-06-29 00:28 UTC, ascheffeapi commented on .github/workflows/lint-and-test.yml
> +      # TODO This is not picking up errors that show up locally.
Not running the pytests

2022-06-29 00:31 UTC, ascheffeapi commented on app/models/payment.py
> +    stripe_event_id = Column(Unicode(DEFAULT_PSQL_STRING_LENGTH), primary_key=True, nullable=False, unique=True)
Would the unique be implied because primary_key is true?

2022-06-29 00:34 UTC, ascheffeapi commented on app/models/payment.py
> +    stripe_event_id = Column(Unicode(DEFAULT_PSQL_STRING_LENGTH), primary_key=True, nullable=False, unique=True)
since  event_date is also a primary key would that mean you could only have 1 unique stripe event id for a specific event_date?

2022-06-29 00:37 UTC, ascheffeapi commented on scripts/pre_start.py
> +max_tries = 60 * 5  # 5 minutes
Maybe Capitalize to indicate constants? I don't know if thats a python convention too

2022-06-29 00:38 UTC, ascheffeapi commented on app/main.py
@bryancusatis Want to add Sentry into this one?

2022-06-30 15:17 UTC, merged